### ISSUE TITLE
Add current XCH price to /stats endpoint

### ISSUE THREAD

**Issue by william-gr** [openchia/api#1]

**Comment by djerfy** [comment]
On my home farmer, I use a Python script (with Telegraf/InfluxDB/Grafana) with this endpoint: `https://api.chiaprofitability.com/market` (JSON output)

**Comment by william-gr** [comment]
I will have to add it to the pool code too for tax purposes when a block is farmed and distributed.
I think I will use https://api.coingecko.com/api/v3/coins/chia since it has more currencies.

**Comment by william-gr** [comment]
Should be fixed in https://github.com/openchia/api/commit/76dbf8b69cb330cb2e447e098f1be1ad5aa7ee51
