### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'method'

### ISSUE THREAD

**Issue by SametBasturkk** [openchia/api#14]
File "/root/api/openchiaapi/api/views.py", line 116, in get_serializer_class
    if self.request.method == 'PUT':
AttributeError: 'NoneType' object has no attribute 'method'

**Comment by SametBasturkk** [comment]
.method removing fix the problem

**Comment by william-gr** [comment]
need more details, cant reproduce

**Comment by SametBasturkk** [comment]
> 

just start to server you will see this error.

**Comment by william-gr** [comment]
Cant reproduce
