### ISSUE TITLE
Firebase Tokens

### ISSUE THREAD

**Issue by BubbleTrouble14** [openchia/api#7]
In order to have push notifications working. The server needs to be able to receive the registered firebase tokens from each device. For this to work I need an api to call and send over the token id to the server which then gets added to list of known tokens to regsiter for the push notifications. 

Server token: pinned

Help references: 
https://medium.com/devmins/firebase-cloud-messaging-api-with-python-6c0755e41eb5 
https://firebase.google.com/docs/cloud-messaging/js/send-multiple

**Comment by william-gr** [comment]
Implemented as fcm_token in PUT /launcher/id
